// Code generation utilities for jizzrug.
// Generates FFI stubs, Makefiles, and interop type declarations.

const EXTENSION_MAP = {
  javascript: "js",
  go: "go",
  rust: "rs",
  zig: "zig",
};

export function generateFFIStubs(lanes) {
  const stubs = {};

  if (lanes.includes("rust") && lanes.includes("javascript")) {
    stubs["ffi_rust_js.rs"] = [
      "// FFI stub: Rust <-> JavaScript (wasm-bindgen pattern)",
      "use wasm_bindgen::prelude::*;",
      "",
      "#[wasm_bindgen]",
      'extern "C" {',
      "    #[wasm_bindgen(js_namespace = console)]",
      "    fn log(s: &str);",
      "}",
      "",
      "#[wasm_bindgen]",
      "pub fn greet(name: &str) -> String {",
      '    format!("hello, {name}")',
      "}",
      "",
    ].join("\n");
  }

  if (lanes.includes("go") && lanes.includes("rust")) {
    stubs["ffi_go_rust.go"] = [
      "package main",
      "",
      "// FFI stub: Go -> Rust (cgo pattern)",
      '// #cgo LDFLAGS: -L. -lrust_ffi',
      '// #include "rust_ffi.h"',
      'import "C"',
      "",
      "func CallRust() {",
      "    // C.rust_exported_function()",
      "}",
      "",
    ].join("\n");
  }

  if (lanes.includes("zig") && lanes.includes("rust")) {
    stubs["ffi_zig_rust.zig"] = [
      "// FFI stub: Zig <-> Rust (C ABI interop)",
      'const c = @cImport({',
      '    @cInclude("rust_ffi.h");',
      "});",
      "",
      "pub export fn zig_entry() void {",
      "    // c.rust_exported_function();",
      "}",
      "",
    ].join("\n");
  }

  return stubs;
}

export function generateMakefile(lanes, outputDir) {
  const lines = [
    "# Generated by jizzrug codegen",
    `.PHONY: all clean`,
    "",
    `OUT_DIR := ${outputDir || "dist"}`,
    "",
  ];

  const targets = [];

  if (lanes.includes("javascript")) {
    lines.push("js: $(OUT_DIR)/main.js");
    lines.push("\t@echo \"JavaScript lane ready\"");
    lines.push("");
    targets.push("js");
  }

  if (lanes.includes("go")) {
    lines.push("go: $(OUT_DIR)/main.go");
    lines.push("\tcd $(OUT_DIR) && go build -o main_go main.go");
    lines.push("");
    targets.push("go");
  }

  if (lanes.includes("rust")) {
    lines.push("rust: $(OUT_DIR)/main.rs");
    lines.push("\trustc $(OUT_DIR)/main.rs -o $(OUT_DIR)/main_rust");
    lines.push("");
    targets.push("rust");
  }

  if (lanes.includes("zig")) {
    lines.push("zig: $(OUT_DIR)/main.zig");
    lines.push("\tzig build-exe $(OUT_DIR)/main.zig");
    lines.push("");
    targets.push("zig");
  }

  lines.splice(1, 0, `all: ${targets.join(" ")}`);

  lines.push("clean:");
  lines.push("\trm -rf $(OUT_DIR)/*.o $(OUT_DIR)/main_go $(OUT_DIR)/main_rust");
  lines.push("");

  return lines.join("\n");
}

export function generateInteropTypes(program) {
  const types = {};
  const lanes = [...new Set(program.segments.map((s) => s.language))];

  if (lanes.includes("javascript")) {
    const labels = program.segments
      .filter((s) => s.label && s.language === "javascript")
      .map((s) => s.label);
    const dtsLines = [
      "// Generated type declarations for jizzrug JS lane",
      "declare module 'jizzrug' {",
    ];
    for (const label of labels) {
      dtsLines.push(`  export function ${label}(): void;`);
    }
    dtsLines.push("}", "");
    types["jizzrug.d.ts"] = dtsLines.join("\n");
  }

  if (lanes.includes("rust")) {
    const labels = program.segments
      .filter((s) => s.label && s.language === "rust")
      .map((s) => s.label);
    const headerLines = [
      "// Generated header for jizzrug Rust lane (C ABI)",
      "#ifndef JIZZRUG_RUST_FFI_H",
      "#define JIZZRUG_RUST_FFI_H",
      "",
    ];
    for (const label of labels) {
      headerLines.push(`void ${label}(void);`);
    }
    headerLines.push("", "#endif", "");
    types["jizzrug_rust_ffi.h"] = headerLines.join("\n");
  }

  return types;
}
