import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const LANGUAGE_ALIASES = new Map([
  ["go", "go"],
  ["golang", "go"],
  ["javascript", "javascript"],
  ["js", "javascript"],
  ["node", "javascript"],
  ["rs", "rust"],
  ["rust", "rust"],
  ["zig", "zig"],
]);

const EXTENSIONS = {
  go: "go",
  javascript: "js",
  rust: "rs",
  zig: "zig",
};

const COMMENT_PREFIX = {
  go: "//",
  javascript: "//",
  rust: "//",
  zig: "//",
};

const SOURCE_EXTENSIONS = [".jizz", ".jizzrug", ".jr"];

export class ParseError extends Error {}

function canonicalLane(rawLane) {
  const canonical = LANGUAGE_ALIASES.get(rawLane.trim().toLowerCase());
  if (!canonical) {
    throw new ParseError(`Unsupported lane '${rawLane}'.`);
  }
  return canonical;
}

export function parseProgram(source) {
  const lines = source.split(/\r?\n/);
  const segments = [];
  let index = 0;
  let nextId = 1;

  while (index < lines.length) {
    const rawLine = lines[index];
    const stripped = rawLine.trim();

    if (!stripped || stripped.startsWith("#")) {
      index += 1;
      continue;
    }

    const fenceMatch = stripped.match(/^```([A-Za-z0-9_+-]+)(?:\s+(.*))?$/);
    if (fenceMatch) {
      const lane = canonicalLane(fenceMatch[1]);
      const label = fenceMatch[2] ? fenceMatch[2].trim() : null;
      const blockStart = index + 1;
      index += 1;
      const blockLines = [];
      while (index < lines.length && lines[index].trim() !== "```") {
        blockLines.push(lines[index]);
        index += 1;
      }
      if (index >= lines.length) {
        throw new ParseError(`Unterminated fenced block starting on line ${blockStart}.`);
      }
      segments.push({
        id: nextId,
        language: lane,
        kind: "block",
        label,
        lineStart: blockStart,
        source: blockLines.join("\n").replace(/\s+$/, ""),
      });
      nextId += 1;
      index += 1;
      continue;
    }

    const colonIndex = rawLine.indexOf(":");
    if (colonIndex !== -1) {
      const lane = canonicalLane(rawLine.slice(0, colonIndex));
      const sourceText = rawLine.slice(colonIndex + 1).trimStart();
      segments.push({
        id: nextId,
        language: lane,
        kind: "line",
        label: null,
        lineStart: index + 1,
        source: sourceText,
      });
      nextId += 1;
      index += 1;
      continue;
    }

    throw new ParseError(`Could not parse line ${index + 1}: '${rawLine}'.`);
  }

  return { segments };
}

function renderLane(language, segments) {
  const comment = COMMENT_PREFIX[language];
  const lines = [
    `${comment} Generated by the jizzrug bootstrap runtime`,
    `${comment} Lane: ${language}`,
    "",
  ];

  for (const segment of segments) {
    lines.push(`${comment} segment ${segment.id} (${segment.kind}) from source line ${segment.lineStart}`);
    if (segment.label) {
      lines.push(`${comment} label: ${segment.label}`);
    }
    if (segment.source) {
      lines.push(segment.source);
    }
    lines.push("");
  }

  return `${lines.join("\n").replace(/\s+$/, "")}\n`;
}

export async function compileSource(sourcePath, outDir) {
  const source = await fs.readFile(sourcePath, "utf8");
  const program = parseProgram(source);
  await fs.mkdir(outDir, { recursive: true });

  const grouped = new Map();
  const manifest = {
    language: "jizzrug",
    version: "0.1.0",
    source: path.basename(sourcePath),
    outputs: [],
    segments: [],
  };

  for (const segment of program.segments) {
    const laneSegments = grouped.get(segment.language) ?? [];
    laneSegments.push(segment);
    grouped.set(segment.language, laneSegments);
    manifest.segments.push({
      id: segment.id,
      language: segment.language,
      kind: segment.kind,
      label: segment.label,
      lineStart: segment.lineStart,
    });
  }

  for (const language of [...grouped.keys()].sort()) {
    const outputName = `main.${EXTENSIONS[language]}`;
    const outputPath = path.join(outDir, outputName);
    await fs.writeFile(outputPath, renderLane(language, grouped.get(language)), "utf8");
    manifest.outputs.push({ language, path: outputName });
  }

  await fs.writeFile(path.join(outDir, "plan.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return manifest;
}

async function listSourceFiles(rootDir) {
  const entries = await fs.readdir(rootDir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listSourceFiles(entryPath)));
      continue;
    }
    if (SOURCE_EXTENSIONS.some((ext) => entry.name.endsWith(ext))) {
      files.push(entryPath);
    }
  }

  return files;
}

export async function bootstrapTree(outDir, treeRoot = repoRoot()) {
  const sourceRoots = ["jizzrug", "rizz", "squirt", "examples"];
  const units = [];

  await fs.mkdir(outDir, { recursive: true });

  for (const sourceRoot of sourceRoots) {
    const absoluteRoot = path.join(treeRoot, sourceRoot);
    const files = await listSourceFiles(absoluteRoot);
    files.sort();
    for (const file of files) {
      const relativeSource = path.relative(treeRoot, file);
      const unitDir = path.join(
        outDir,
        relativeSource.replace(/\.(jizz|jizzrug|jr)$/, "").replaceAll(path.sep, "__"),
      );
      const manifest = await compileSource(file, unitDir);
      units.push({
        source: relativeSource,
        outDir: path.relative(outDir, unitDir) || ".",
        outputs: manifest.outputs,
      });
    }
  }

  const bootstrapManifest = {
    language: "jizzrug",
    mode: "bootstrap",
    units,
  };
  await fs.writeFile(
    path.join(outDir, "bootstrap-plan.json"),
    `${JSON.stringify(bootstrapManifest, null, 2)}\n`,
    "utf8",
  );
  return bootstrapManifest;
}

function repoRoot() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
}

function printHelp() {
  console.log(`usage: rizz <command> [options]

commands:
  cum <source> [--out DIR] [--json]     Run the Computer Unified Memory dispatcher
  bootstrap [--out DIR] [--json]        Compile the repo .jizz source tree
  help                                  Show this help text`);
}

function parseFlags(args) {
  let outDir = null;
  let json = false;
  const positional = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--json") {
      json = true;
      continue;
    }
    if (arg === "--out") {
      outDir = args[index + 1];
      index += 1;
      continue;
    }
    positional.push(arg);
  }

  return { outDir, json, positional };
}

async function runCum(args) {
  const { outDir, json, positional } = parseFlags(args);
  const source = positional[0];
  if (!source) {
    throw new Error("cum requires a source path.");
  }
  if (!SOURCE_EXTENSIONS.some((ext) => source.endsWith(ext))) {
    throw new Error("source must end in .jizz, .jizzrug, or .jr");
  }
  const manifest = await compileSource(source, outDir ?? "dist/jizzrug");
  if (json) {
    console.log(JSON.stringify(manifest, null, 2));
  } else {
    const outputs = manifest.outputs.map((item) => item.path).join(", ");
    console.log(`Compiled ${source} into ${outDir ?? "dist/jizzrug"}: ${outputs}`);
  }
}

async function runBootstrap(args) {
  const { outDir, json } = parseFlags(args);
  const manifest = await bootstrapTree(outDir ?? "out/bootstrap");
  if (json) {
    console.log(JSON.stringify(manifest, null, 2));
  } else {
    console.log(`Bootstrapped ${manifest.units.length} jizzrug source units into ${outDir ?? "out/bootstrap"}`);
  }
}

export async function main(argv) {
  const [command, ...args] = argv;

  if (!command || command === "help" || command === "--help" || command === "-h") {
    printHelp();
    return 0;
  }

  if (command === "cum") {
    await runCum(args);
    return 0;
  }

  if (command === "bootstrap") {
    await runBootstrap(args);
    return 0;
  }

  throw new Error(`Unknown command: ${command}`);
}
